server:
  port: 8093
spring:
  application:
    name: Zpain-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/zpain_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
  redis:
    database: 0
    host: localhost
    port: 6379
  cloud:
    nacos:
      config:
        group: zpain-auth
        namespace: ${spring.cloud.nacos.discovery.namespace}
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
      discovery:
        namespace: 164265e8-9bd8-424d-a687-94cca4083a21
        server-addr: localhost:8848
        group: zpain
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.zpain.auth.entity
jwt:
  expiration: 600000
  header: Authorization
  secret: mySecret
  tokenHead: 'Bearer '

